version: 0.2

phases:
  install:
    commands:
      - 'cd client/'
      - 'npm install'
  build:
    commands:
      - 'npm run build'
  post_build:
    commands:
      - 'cd ../server'
      - 'npm install'
artifacts:
  files:
    - 'server/**/*'
    - 'client/build/**/*'
    - 'package.json'
