version: 0.2

phases:
  install:
    commands:
      - 'cd client/'
      - 'npm install'
  build:
    commands:
      - 'npm run build'
artifacts:
  files:
    - 'server/**/*'
    - 'client/build/**/*'