version: 0.2

phases:
  install:
    commands:
      - 'cd client/'
      - 'npm install'
  build:
    commands:
      - 'npm run build'
  # post_build:
  #   commands:
  #     - 'cd ../server'
  #     - 'zip ../build.zip *'
  #     - 'cd ..'
  #     - 'zip build.zip -r client/build'
artifacts:
  files:
    - 'server/*'
    - 'client/build/*'
  discard-paths: yes
